#!/usr/bin/env bash
# a script that displays information about subdomains

print_sub_domains () {
    rec=$(dig "$2"."$1" +noall +answer | head -1 | awk '{print $4}')
    ip=$(dig "$2"."$1" +noall +answer | head -1 | awk '{print $5}')
    echo "The subdomain $2 is a $rec record and points to $ip"
}

subdomains=("www" "lb-01" "web-01" "web-02")

if [ "$#" -eq 1 ] ; then
    for str in "${subdomains[@]}"; do
        print_sub_domains "$1" "$str"
    done
else
    print_sub_domains "$1" "$2"
fi
