#!/usr/bin/env bash
# a script that displays information about subdomains

print_sub_domains () {
    ip=$(dig "$2"."$1" +noall +answer | awk '{print $5}')
    echo "The subdomain $2 is a A record and points to $ip"
}

subdomains=("www" "lb-01" "web-01" "web-02")

if [ "$2" == "" ] ; then
    for str in "${subdomains[@]}"; do
        print_sub_domains "$1" "$str"
    done
else
    print_sub_domains "$1" "$2"
fi
