#!/usr/bin/env bash
# A script that installs a nginx server
sudo apt-get update
sudo apt-get install nginx -y
# sudo ufw allow 'Nginx HTTP'
# sudo ufw reload
echo "Hello World!" > index.html
sudo mv index.html > /var/www/html/
# sudo service reload nginx
