#!/usr/bin/env bash
# A script that installs a nginx server
sudo apt-get update
sudo apt-get install nginx -y
sudo chown -R "$USER":"$USER" /var/www
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.goal.com;
    }

    error_page 404 /404.html;
    location = /404.html {
                root /var/www/html;
                internal;
    }
}
" > /etc/nginx/sites-available/default
sudo service nginx restart
