#!/usr/bin/env bash
# Installs and configures an HAProxy server
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get update
sudo apt-get install haproxy=2.8.\* -y
sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/
echo "ENABLED=1" >> /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.copy
printf %s "
listen hbnb
        # listen 80 port
        bind 0.0.0.0:80
        balance            roundrobin
        server             150155-web-01 34.204.81.235:80 check
        server             150155-web-02 18.234.107.45:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
