#!/usr/bin/env bash
# Installs and configures an HAProxy server
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy=2.8.\* -y
sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/
echo "ENABLED=1" >> /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.copy
# add to the end
# define frontend ( any name is OK for [www] )
printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen www
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 150155-web-01 34.204.81.235:80 check
    server 150155-web-02 18.234.107.45:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
