#!/usr/bin/env bash
# An init script that runs "manage_my_process"
if [[ $1 == 'start' ]]
then
    ./manage_my_process &
    echo "manage_my_process started"
    pgrep bash -la | awk '$3=="./manage_my_process" {print $1}' > /var/run/my_process.pid
elif [[ $1 == 'stop' ]]
then
    pgrep bash -la | awk '$3=="./manage_my_process" {print $1}' | xargs kill -TERM
    rm /var/run/my_process.pid
    echo "manage_my_process has stopped"
elif [[ $1 == 'restart' ]]
then
    pgrep bash -la | awk '$3=="./manage_my_process" {print $1}' | xargs kill -TERM
    rm /var/run/my_process.pid
    ./manage_my_process &
    echo "manage_my_process restarted"
    pgrep bash -la | awk '$3=="./manage_my_process" {print $1}' > /var/run/my_process.pid
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
