#!/usr/bin/env bash
# An init script that runs "manage_my_process"
set -e
if [[ $1 == 'start' ]]
then
    ./manage_my_process &
    echo "manage_my_process started"
    echo "$!" > /var/run/my_process.pid
elif [[ $1 == 'stop' ]]
then
    xargs kill -TERM < /var/run/my_process.pid
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [[ $1 == 'restart' ]]
then
    if [ -e /var/run/my_process.pid ]
    then
        xargs kill -TERM < /var/run/my_process.pid
        rm /var/run/my_process.pid
    fi
    ./manage_my_process &
    echo "manage_my_process restarted"
    echo "$!" > /var/run/my_process.pid
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi

exit 0
