#!/usr/bin/env bash
# A script that prints 1 to 100, fizzbuzz format
count=1
while [ $count -le 100 ]
do
    if [ $((count%15)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((count%3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((count%5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$count"
    fi
    ((count = count + 1))
done
