#!/usr/bin/env bash
# A script that displays the visitor IP along with the HTTP status code from the Apache log file.
awk '{a[$1,$9]+=1} END {for (i in a) {print a[i], i}}' apache-access.log | sort -rn