#!/usr/bin/env bash
# A script that prints "Best School" 10 times using a for loop
count=0
while [ $count -lt 10 ]
do
	echo "Best School"
    if [ "$count" -eq 8 ]
    then
        echo "Hi"
    fi
	((count = count + 1))
done
