#!/usr/bin/env bash
# A script that prints "Best School" 10 times using a for loop
count=1
while [ $count -lt 21 ]
do
    echo "$count"
    case $count in
    4)
        echo "bad luck from China"
        ;;
    9)
        echo "bad luck from Japan"
        ;;
    17)
        echo "bad luck from Italy"
        ;;
    esac
	((count = count + 1))
done
