#!/usr/bin/env bash
# A  Bash script that configures an Ubuntu server with the below requirements.
#+ Requirements:
#+ localhost resolves to 127.0.0.2
#+ facebook.com resolves to 8.8.8.8.

cp /etc/hosts newfile
echo "127.0.0.1 localhost" > newfile
echo "8.8.8.8 facebook.com" >> newfile
cp -f newfile /etc/hosts
