#!/usr/bin/env bash
# A  Bash script that configures an Ubuntu server with the below requirements.
#+ Requirements:
#+ localhost resolves to 127.0.0.2
#+ facebook.com resolves to 8.8.8.8.

cp /etc/hosts newfile
sed -i "s/127.0.0.1/127.0.0.2/" newfile
sed -i "/127.0.0.2/a 8.8.8.8 \tfacebook.com" newfile
cp -f newfile /etc/hosts
